# Variables are defined in `${workspaceFolder}.vscode/settings.json`.

### Statsu
GET http://{{host}}:{{ctlApiPort}}/{{version}}/processes

### CPU layout
GET http://{{host}}:{{ctlApiPort}}/{{version}}/cpu_layout

### CPU usage
GET http://{{host}}:{{ctlApiPort}}/{{version}}/cpu_usage