# Variables are defined in `${workspaceFolder}.vscode/settings.json`.

### Statsu
GET http://{{host}}:{{ctlApiPort}}/{{version}}/processes
content-type: application/json

### CPU layout
GET http://{{host}}:{{ctlApiPort}}/{{version}}/cpu_layout
content-type: application/json

### CPU usage
GET http://{{host}}:{{ctlApiPort}}/{{version}}/cpu_usage
content-type: application/json