# Variables are defined in `${workspaceFolder}.vscode/settings.json`.

### Statsu
GET http://{{host}}:{{ctlApiPort}}/{{version}}/primary/status
content-type: application/json

### Add port
PUT http://{{host}}:{{ctlApiPort}}/{{version}}/primary/ports
content-type: application/json

{
    "action": "add",
    "port": "ring:1"
}

### Delete port
PUT http://{{host}}:{{ctlApiPort}}/{{version}}/primary/ports
content-type: application/json

{
    "action": "del",
    "port": "ring:0"
}

### Start forwarding
PUT http://{{host}}:{{ctlApiPort}}/{{version}}/primary/forward

{"action": "start"}

### Stop forwarding
PUT http://{{host}}:{{ctlApiPort}}/{{version}}/primary/forward

{"action": "stop"}

### Clear statistics
DELETE http://{{host}}:{{ctlApiPort}}/{{version}}/primary/status
content-type: application/json

### Patch ports
PUT http://{{host}}:{{ctlApiPort}}/{{version}}/primary/patches

{
    "src": "ring:0",
    "dst": "ring:1"
}

### Reset patches
DELETE http://{{host}}:{{ctlApiPort}}/{{version}}/primary/patches

### Launch secondary process
PUT http://{{host}}:{{ctlApiPort}}/{{version}}/primary/launch

{
    "proc_name": "spp_nfv",
    "client_id": "1",
    "eal": {
        "-m": "512",
        "-l": "2-3",
        "--proc-type": "secondary"
    },
    "app": {
        "-n": "1",
        "-s": "{{host}}:{{secPort}}"
    }
}